name: test

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: find
        run: |
          echo 'result<<EOF' | tee -a "$GITHUB_OUTPUT"
          find . \( -name '*.sh' -o -name '*.bash' \) -print0 | xargs -0 echo | tee -a "$GITHUB_OUTPUT"
          echo 'EOF' | tee -a "$GITHUB_OUTPUT"
      - uses: docker://koalaman/shellcheck:stable
        with:
          args: ${{ steps.find.outputs.result }}
  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - command: |
              test -z "$(gw list)"
              gw add test-branch
              gw list | grep 'test-branch'
              original_dir="$(pwd)"
              gw cd test-branch
              current_dir="$(pwd)"
              gw back
              test "$current_dir" != "$original_dir"
              gw remove test-branch
              test -z "$(gw list)"
          - command: |
              gw -h
              gw --help
          - command: |
              gw -v
              gw --version
          - command: |
              gw || test "$?" -eq 4
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '<41898282+github-actions[bot]@users.noreply.github.com>'
          git config --global init.defaultBranch main
      - run: |
          touch test.txt
          git add test.txt
          git checkout -b test-branch
          git commit -m 'chore: add test.txt'
      - run: |
          shopt -s expand_aliases
          source git-worktree.bash
          ${{ matrix.command }}
